name = "hankv2016-blog"
compatibility_date = "2024-01-01"

# Cloudflare Pages 项目配置
# 部署命令: npx wrangler pages deploy . --branch main
# 本地开发: npx wrangler pages dev .

# KV 绑定
[[kv_namespaces]]
binding = "BLOG_KV"
id = "68863e0696e4494a90c5b757f7bebb6a"

[vars]
ADMIN_PASSWORD = "change-me-please"
SITE_TITLE = "Hankv Blog"
